spring.application.name=demo
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.application.name=demo
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

scheduler.group-category-activation.cron=0 * * * * *

jwt.secret=${JWT_SECRET:avvyLoZsnoOmlfX26ee83pMd14/UGaKwgGzMqESLS/w=}
jwt.expiration-ms=3600000
logging.level.org.springframework.security=DEBUG
