spring.application.name=demo
spring.datasource.url=jdbc:oracle:thin:@10.10.0.202:1521:orcl
spring.datasource.username=DEMO
spring.datasource.password=DEMO
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.application.name=demo
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
#spring.datasource.username=system
#spring.datasource.password=25122002

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

scheduler.group-category-activation.cron=0/5 * * * * ?
spring.quartz.job-store-type=memory
